GET {{baseUrl}}/grammar HTTP/1.1
Content-Type: application/json
token: {{token}}


###


GET {{baseUrl}}/grammar/1 HTTP/1.1
Content-Length: application/json
token: {{token}}


###


POST {{baseUrl}}/grammar HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "LanguageName": "English",
    "ReadingLevel": "Orta Seviye",
    "WritingLevel": "Orta Seviye",
    "SpeakingLevel": "Orta Seviye"
}


###


PUT {{baseUrl}}/grammar HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "Id": "1",
    "LanguageName": "Türkçe",
    "ReadingLevel": "Orta Seviye",
    "writingLevel": "Orta Seviye",
    "SpeakingLevel": "Orta Seviye"
}


###


DELETE {{baseUrl}}/grammar HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "Id": 1
}