GET {{baseUrl}}/hobbies HTTP/1.1
Content-Type: application/json
token: {{token}}


###


GET {{baseUrl}}/hobbies/11 HTTP/1.1
Content-Type: application/json
token: {{token}}


###


POST {{baseUrl}}/hobbies HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "HobbyName": "Golf"
}


###


PUT {{baseUrl}}/hobbies HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "Id": 1,
    "HobbyName": "PC Gaming"
}