GET {{baseUrl}}/project HTTP/1.1
Content-Type: application/json
token: {{token}}


###


POST {{baseUrl}}/project HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "ProjectName": "CV-Project Admin",
    "Description": "We are adding front-end variables."
}


###


PUT {{baseUrl}}/project HTTP/1.1
Content-Type: application/json
token: {{token}} 

{
    "Id": 21,
    "ProjectName": "CV-Project Front-End",
    "Description": "We are showing all we made."
}


###


DELETE {{baseUrl}}/project HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "Id": 51
}